                                    <option value="Afghan">Afghan</option>
                                    <option value="African">African</option>
                                    <option value="Albanian">Albanian</option>
                                    <option value="Alcohol">Alcohol</option>
                                    <option value="American">American</option>
                                    <option value="Argentinian">Argentinian</option>
                                    <option value="Asian">Asian</option>
                                    <option value="Australian">Australian</option>
                                    <option value="Austrian">Austrian</option>
                                    <option value="Bagels">Bagels</option>
                                    <option value="Bakery">Bakery</option>
                                    <option value="BBQ">BBQ</option>
                                    <option value="Belgian">Belgian</option>
                                    <option value="Brazilian">Brazilian</option>
                                    <option value="Breakfast">Breakfast</option>
                                    <option value="British">British</option>
                                    <option value="Burmese">Burmese</option>
                                    <option value="Cajun">Cajun</option>
                                    <option value="Californian">Californian</option>
                                    <option value="Calzones">Calzones</option>
                                    <option value="Cambodian">Cambodian</option>
                                    <option value="Cantonese">Cantonese</option>
                                    <option value="Caribbean">Caribbean</option>
                                    <option value="Cheesesteaks">Cheesesteaks</option>
                                    <option value="Chicken">Chicken</option>
                                    <option value="Chili">Chili</option>
                                    <option value="Chinese">Chinese</option>
                                    <option value="Classic">Classic</option>
                                    <option value="Coffee and Tea">Coffee and Tea</option>
                                    <option value="Colombian">Colombian</option>
                                    <option value="Costa Rican">Costa Rican</option>
                                    <option value="Crepes">Crepes</option>
                                    <option value="Cuban">Cuban</option>
                                    <option value="Deli">Deli</option>
                                    <option value="Dessert">Dessert</option>
                                    <option value="Dim Sum">Dim Sum</option>
                                    <option value="Diner">Diner</option>
                                    <option value="Dinner">Dinner</option>
                                    <option value="Dominican">Dominican</option>
                                    <option value="Eclectic">Eclectic</option>
                                    <option value="Ecuadorian">Ecuadorian</option>
                                    <option value="Egyptian">Egyptian</option>
                                    <option value="El Salvadoran">El Salvadoran</option>
                                    <option value="Empanadas">Empanadas</option>
                                    <option value="English">English</option>
                                    <option value="Ethiopian">Ethiopian</option>
                                    <option value="Filipino">Filipino</option>
                                    <option value="Fine Dining">Fine Dining</option>
                                    <option value="French">French</option>
                                    <option value="Fresh Fruits">Fresh Fruits</option>
                                    <option value="Frozen Yogurt">Frozen Yogurt</option>
                                    <option value="German">German</option>
                                    <option value="Gluten-Free">Gluten-Free</option>
                                    <option value="Greek">Greek</option>
                                    <option value="Grill">Grill</option>
                                    <option value="Guatemalan">Guatemalan</option>
                                    <option value="Gyro">Gyro</option>
                                    <option value="Haitian">Haitian</option>
                                    <option value="Halal">Halal</option>
                                    <option value="Hamburgers">Hamburgers</option>
                                    <option value="Hawaiian">Hawaiian</option>
                                    <option value="Healthy">Healthy</option>
                                    <option value="Hoagies">Hoagies</option>
                                    <option value="Hot Dogs">Hot Dogs</option>
                                    <option value="Ice Cream">Ice Cream</option>
                                    <option value="Indian">Indian</option>
                                    <option value="Indonesian">Indonesian</option>
                                    <option value="Irish">Irish</option>
                                    <option value="Italian">Italian</option>
                                    <option value="Jamaican">Jamaican</option>
                                    <option value="Japanese">Japanese</option>
                                    <option value="Kids Menu">Kids Menu</option>
                                    <option value="Korean">Korean</option>
                                    <option value="Kosher">Kosher</option>
                                    <option value="Kosher-Style">Kosher-Style</option>
                                    <option value="Late Night">Late Night</option>
                                    <option value="Latin American">Latin American</option>
                                    <option value="Lebanese">Lebanese</option>
                                    <option value="Low Carb">Low Carb</option>
                                    <option value="Low Fat">Low Fat</option>
                                    <option value="Lunch">Lunch</option>
                                    <option value="Lunch Specials">Lunch Specials</option>
                                    <option value="Malaysian">Malaysian</option>
                                    <option value="Mandarin">Mandarin</option>
                                    <option value="Mediterranean">Mediterranean</option>
                                    <option value="Mexican">Mexican</option>
                                    <option value="Middle Eastern">Middle Eastern</option>
                                    <option value="Mongolian">Mongolian</option>
                                    <option value="Moroccan">Moroccan</option>
                                    <option value="Nepalese">Nepalese</option>
                                    <option value="New American">New American</option>
                                    <option value="Noodles">Noodles</option>
                                    <option value="Organic">Organic</option>
                                    <option value="Pakistani">Pakistani</option>
                                    <option value="Pasta">Pasta</option>
                                    <option value="Persian">Persian</option>
                                    <option value="Peruvian">Peruvian</option>
                                    <option value="Pitas">Pitas</option>
                                    <option value="Pizza">Pizza</option>
                                    <option value="Polish">Polish</option>
                                    <option value="Portuguese">Portuguese</option>
                                    <option value="Potato">Potato</option>
                                    <option value="Pub Food">Pub Food</option>
                                    <option value="Puerto Rican">Puerto Rican</option>
                                    <option value="Ribs">Ribs</option>
                                    <option value="Russian">Russian</option>
                                    <option value="Salads">Salads</option>
                                    <option value="Sandwiches">Sandwiches</option>
                                    <option value="Scandinavian">Scandinavian</option>
                                    <option value="Seafood">Seafood</option>
                                    <option value="Senegalese">Senegalese</option>
                                    <option value="Shakes">Shakes</option>
                                    <option value="Smoothies and Juices">Smoothies and Juices</option>
                                    <option value="Soul Food">Soul Food</option>
                                    <option value="Soup">Soup</option>
                                    <option value="South African">South African</option>
                                    <option value="South American">South American</option>
                                    <option value="Southern">Southern</option>
                                    <option value="Southwestern">Southwestern</option>
                                    <option value="Spanish">Spanish</option>
                                    <option value="Steak">Steak</option>
                                    <option value="Subs">Subs</option>
                                    <option value="Sushi">Sushi</option>
                                    <option value="Szechwan">Szechwan</option>
                                    <option value="Taiwanese">Taiwanese</option>
                                    <option value="Tapas">Tapas</option>
                                    <option value="Tex-Mex">Tex-Mex</option>
                                    <option value="Thai">Thai</option>
                                    <option value="Tibetan">Tibetan</option>
                                    <option value="Turkish">Turkish</option>
                                    <option value="Ukrainian">Ukrainian</option>
                                    <option value="Vegan">Vegan</option>
                                    <option value="Vegetarian">Vegetarian</option>
                                    <option value="Venezuelan">Venezuelan</option>
                                    <option value="Vietnamese">Vietnamese</option>
                                    <option value="Wings">Wings</option>
                                    <option value="Wraps">Wraps</option>
